# Generated by Django 5.0.1 on 2024-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangerate",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="chf_to_pln",
            field=models.FloatField(blank=True, null=True, verbose_name="CHF/PLN"),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="eur_to_pln",
            field=models.FloatField(blank=True, null=True, verbose_name="EUR/PLN"),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="usd_to_pln",
            field=models.FloatField(blank=True, null=True, verbose_name="USD/PLN"),
        ),
    ]
