# Generated by Django 5.0.1 on 2024-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency_app", "0002_remove_exchangerate_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="chf_to_usd",
            field=models.FloatField(blank=True, null=True, verbose_name="CHF/USD"),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="eur_to_usd",
            field=models.FloatField(blank=True, null=True, verbose_name="EUR/USD"),
        ),
    ]
