# Generated by Django 5.0.1 on 2024-01-17 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency_app", "0003_exchangerate_chf_to_usd_exchangerate_eur_to_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
